Add printf attribute to usage function and fix warnings it causes
gcc suggested it:
 xset.c: In function ‘usage’:
 xset.c:1577:2: warning: function might be possible candidate for ‘gnu_printf’
  format attribute [-Wmissing-format-attribute]

But adding it unveiled many complaints about extra trailing NULL args
from before usage took a variable number of arguments:

xset.c:186:3: warning: too many arguments for format [-Wformat-extra-args]
xset.c:193:2: warning: too many arguments for format [-Wformat-extra-args]
xset.c:362:3: warning: too many arguments for format [-Wformat-extra-args]
xset.c:370:3: warning: too many arguments for format [-Wformat-extra-args]
xset.c:376:3: warning: too many arguments for format [-Wformat-extra-args]
xset.c:382:3: warning: too many arguments for format [-Wformat-extra-args]
xset.c:388:3: warning: too many arguments for format [-Wformat-extra-args]
xset.c:402:7: warning: too many arguments for format [-Wformat-extra-args]
xset.c:425:7: warning: too many arguments for format [-Wformat-extra-args]
xset.c:542:4: warning: too many arguments for format [-Wformat-extra-args]
xset.c:735:3: warning: too many arguments for format [-Wformat-extra-args]

so those were deleted.

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>